services:
  web:
    build:
      context: .
    command: gunicorn bus_service.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120
    env_file:
      - ./.env.prod 
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static:/bus_service/static
      - media:/bus_service/media
    networks:
      - bus_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - bus_network

  nginx:
    build: ./nginx
    ports:
      - "1337:80" 
    depends_on:
      - web 
    volumes:
      - ./static:/bus_service/static/
      - ./media:/bus_service/media/
    networks:
      - bus_network

volumes:
  static:
  media:
  postgres_data:
networks:
  bus_network:
    driver: bridge