
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bus_service
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=bus_service.settings
      - SQL_ENGINE=django.db.backends.postgresql
      - POSTGRES_DB=Django_Bus_WebApplication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hphphphp
      - SQL_HOST=db
      - SQL_PORT=5432
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hphphphp
      - POSTGRES_DB=Django_Bus_WebApplication
    

volumes:
  postgres_data: