services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use a production-specific Dockerfile if needed.
    command: gunicorn bus_service.wsgi:application --bind 0.0.0.0:1337 --workers 3 --threads 2 --timeout 120 
    volumes:
      - ./bus/static:/bus_service/staticfiles/
      - ./media:/bus_service/mediafiles/
    expose:
      - "1337"
    env_file:
      - ./.env.prod 
    depends_on:
      - db
  db:
    image: postgres:15-alpine
#      POSTGRES_DB: Django_Bus_WebApplication_prod
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: hphphphp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx 
    ports:
      - "1337:80" 
    depends_on:
      - web 
    volumes:
      - ./bus/static:/bus_service/staticfiles/
      - ./media:/bus_service/mediafiles/

volumes:
  postgres_data:
  static_volume:
  media_volume:
