services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./bus/static:/bus_service/staticfiles/
      - ./media:/bus_service/media/
    expose:
      - "1337"
    env_file:
      - ./.env.prod 
    depends_on:
      - db
    ports:
      - "1337:1337"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - "8000:80" 
    depends_on:
      - web 
    volumes:
      - ./static:/bus_service/
      - ./staticfiles:/bus_service/staticfiles/
      - ./media:/bus_service/media/

volumes:
  postgres_data:
  static_volume:
  media_volume: