# Generated by Django 4.2.18 on 2025-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
