# Generated by Django 4.2.18 on 2025-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_buses',
            field=models.ManyToManyField(related_name='editable_by', to='bus.bus'),
        ),
    ]
