# Generated by Django 4.2.18 on 2025-02-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.route'),
        ),
    ]
