# Generated by Django 4.2.18 on 2025-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_days_of_week_running_alter_seat_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
