# Generated by Django 4.2.18 on 2025-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_busroute_otps_stop_alter_bus_bus_number_routestop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='otp_code',
            field=models.PositiveIntegerField(),
        ),
    ]
