# Generated by Django 4.2.18 on 2025-02-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='fare',
            new_name='base_fare_per_hour',
        ),
        migrations.AddField(
            model_name='route',
            name='stop_durations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
