# Generated by Django 4.2.18 on 2025-01-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_booking_seats_booked_user_can_change_buses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.PositiveIntegerField(max_length=50, unique=True),
        ),
    ]
