# Generated by Django 4.2.18 on 2025-02-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
