# Generated by Django 4.2.18 on 2025-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_rename_fare_bus_base_fare_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.AlterField(
            model_name='route',
            name='intermediate_stops',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop_durations',
            field=models.JSONField(default=dict),
        ),
    ]
