# Generated by Django 4.2.18 on 2025-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_bus_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
