# Generated by Django 4.2.18 on 2025-02-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_remove_user_email_otp_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_classes',
            field=models.CharField(default=-2, help_text="Seat counts for General, Sleeper, and Luxury classes, separated by hyphens. Example: '50-30-10'", max_length=11),
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('General', 'General'), ('Sleeper', 'Sleeper'), ('Luxury', 'Luxury')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
    ]
