# Generated by Django 4.2.18 on 2025-02-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_otps_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_class',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='seatclass',
            name='seating_arrangement',
        ),
        migrations.RemoveField(
            model_name='seatclass',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='routestop',
            name='duration_to_next_stop',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_end', to='bus.routestop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_start', to='bus.routestop'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus.bus')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.seatclass')),
            ],
            options={
                'unique_together': {('bus', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, null=True, to='bus.seat'),
        ),
    ]
