# Generated by Django 4.2.18 on 2025-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_bus_seat_classes_seatclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.CharField(default=-2, help_text="Booked Seat counts for General, Sleeper, and Luxury classes, separated by hyphens. Example: '50-30-10'", max_length=11),
        ),
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.CharField(default=-2, help_text="Available Seat counts for General, Sleeper, and Luxury classes, separated by hyphens. Example: '50-30-10'", max_length=11),
        ),
    ]
