# Generated by Django 4.2.18 on 2025-02-15 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_remove_route_duration_alter_route_intermediate_stops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(default=datetime.date(2025, 2, 15)),
        ),
        migrations.AddField(
            model_name='bus',
            name='operating_days',
            field=models.JSONField(default=list),
        ),
    ]
