# Generated by Django 4.2.18 on 2025-02-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_booking_travel_date_bus_operating_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
