# Generated by Django 4.2.18 on 2025-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_alter_booking_seats_booked_alter_bus_available_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatClass',
        ),
    ]
