# Generated by Django 4.2.18 on 2025-02-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_delete_seatclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.CharField(help_text="Available Seat counts for General, Sleeper, and Luxury classes, separated by hyphens. Example: '50-30-10'", max_length=11),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_classes',
            field=models.CharField(help_text="Seat counts for General, Sleeper, and Luxury classes, separated by hyphens. Example: '50-30-10'", max_length=11),
        ),
    ]
