# Generated by Django 4.2.18 on 2025-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_alter_bus_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
