# Generated by Django 4.2.18 on 2025-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_remove_bus_id_alter_bus_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='intermediate_stops',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
